from plone.base.interfaces.installable import INonInstallable
from zope.interface import implementer


@implementer(INonInstallable)
class HiddenProfiles:
    # plone-stubs declares both methods as returning None (generated by
    # stubgen from the interface); Plone expects a list of names.
    def getNonInstallableProfiles(self) -> list[str]:  # type: ignore[override]
        """Hide uninstall profile from site-creation and quickinstaller."""
        return [
            "collective.polls:uninstall",
        ]

    def getNonInstallableProducts(self) -> list[str]:  # type: ignore[override]
        """Hide the upgrades package from site-creation and quickinstaller."""
        return [
            "collective.polls.upgrades",
        ]
